### ISSUE TITLE
ニックネームじゃなくてユーザー名が出るせいでちょっと分かりにくい

### ISSUE THREAD

**Issue by gamoutatsumi** [wcdi/wcdi-Discord-Slack-bot#4]
`discord.py` のドキュメントを見た感じ `discord.Member.display_name` でニックネームか表示名を取ってこれるみたいです

**Comment by hashy0917** [comment]
PR出してくれても良いんですよ？

**Comment by gamoutatsumi** [comment]
PR出すつもりで立てたんですけど忙しくてやれてないです

**Comment by hashy0917** [comment]
それでも立ててくれたんだねぇありがとうねぇ

**Comment by hashy0917** [comment]
という事でマージしました。
